blog/urls.py
from django.urls import path

from blog.views import index, detail, archive, category, tag

app_name = 'blog'
urlpatterns = [
    path('', index, name='index'),
    path('post/<int:pk>/', detail, name='detail'),
    path('archives/<int:year>/<int:month>/', archive, name='archive'),
    path('category/<int:cid>/', category, name='category'),
    path('tag/<int:tid>/', tag, name='tag'),

]

comments/urls.py
from django.urls import path

from comments.views import CommentView

app_name = 'comments'
urlpatterns = [
    path('<int:pid>/', CommentView.as_view(), name='comment')
]

third_blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('comment/', include('comments.urls')),
    path('wiki/', include('wiki.urls')),

    path('mdeditor/', include('mdeditor.urls'))
]

# if settings.DEBUG:
#     # static files (images, css, javascript, etc.)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wiki/urls.py
from django.urls import path

from wiki.views import index, WikiDetailView

app_name = 'wiki'
urlpatterns = [
    path('', index, name='index'),
    path('detail/<int:cid>/', WikiDetailView.as_view(), name='detail'),
]

blog/models.py
import markdown
from django.db import models
from django.shortcuts import reverse
from django.utils.html import strip_tags


class Category(models.Model):
    name = models.CharField('分类名', max_length=255)

    class Meta:
        verbose_name_plural = verbose_name = '分类'

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField('标签名', max_length=255)

    class Meta:
        verbose_name_plural = verbose_name = '标签'

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField('标题', max_length=255)
    body = models.TextField('内容')

    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    modified_time = models.DateTimeField('修改时间', auto_now=True)

    excerpt = models.CharField('摘要', max_length=255, blank=True)

    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='分类')

    # 多对多关系会新建一张表, 每一行会存储对应的两个数据间的关系
    tags = models.ManyToManyField('Tag', blank=True, verbose_name='标签')

    class Meta:
        # 后端字段名
        verbose_name_plural = verbose_name = '文章'
        # 自定义排序规则
        ordering = ['-created_time', ]

    def __str__(self):
        return self.title

    # 自定义 get_absolute_url() 方法
    # 返回该文章对应的url链接
    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={'pk': self.id})

    def save(self, *args, **kwargs):
        if self.excerpt == '':
            # 首先实例化一个 Markdown 类，用于渲染 body 的文本。
            # 由于摘要并不需要生成文章目录，所以去掉了目录拓展。
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])

            # 先将 Markdown 文本渲染成 HTML 文本
            # strip_tags 去掉 HTML 文本的全部 HTML 标签
            # 从文本摘取前 54 个字符赋给 excerpt
            self.excerpt = strip_tags(md.convert(self.body))[:128] + '...'

        super().save(*args, **kwargs)

comments/models.py
from django.db import models


class Comment(models.Model):
    name = models.CharField('名字', max_length=50)
    email = models.EmailField('邮箱', blank=True)
    url = models.URLField('网址', blank=True)
    text = models.TextField('内容')
    created_time = models.DateTimeField('创建时间', auto_now=True)
    post = models.ForeignKey('blog.Post', verbose_name='文章', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = verbose_name = '评论'
        ordering = ['-created_time', ]

    def __str__(self):
        return '{}: {}'.format(self.name, self.text[:20])

wiki/models.py
from django.db import models

# Create your models here.

comments/forms.py
from django import forms

from comments.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name',  'email', 'url', 'text']

blog/views.py
import markdown
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.utils.text import slugify
from django.views import View
from markdown.extensions.toc import TocExtension

from blog.models import Post, Category, Tag


def index(request):
    posts = Post.objects.all()
    context = {
        'post_list': posts,
    }
    return render(request, 'blog/index.html', context=context)


def detail(request, pk):
    post = get_object_or_404(Post, id=pk)
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
        TocExtension(slugify=slugify),
    ])
    post.body = md.convert(post.body)
    post.toc = md.toc
    context = {
        'post': post,
    }
    return render(request, 'blog/detail.html', context=context)


def archive(request, year, month):
    # 调用属性, 使用__, 双下划线
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month
                                    )
    print(post_list)
    # post_list = Post.objects.all()
    # for i in post_list:
    #     print(i.created_time, i.created_time.year, i.created_time.month)
    return render(request, 'blog/index.html', context={'post_list': post_list})


def category(request, cid):
    cate = get_object_or_404(Category, pk=cid)
    post_list = cate.post_set.all()
    # post_list = Post.objects.filter(category=cate).order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})


def tag(request, tid):
    tag = get_object_or_404(Tag, pk=tid)
    post_list = tag.post_set.all()
    # post_list = Post.objects.filter(tags=tag).order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})

comments/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View

from blog.models import Post
from comments.forms import CommentForm


class CommentView(View):
    def post(self, request, pid):
        post = get_object_or_404(Post, id=pid)

        form = CommentForm(request.POST)
        if form.is_valid():
            # commit=False 的作用是仅仅利用表单的数据生成 Comment 模型类的实例，
            # 但还不保存评论数据到数据库。
            comment = form.save(commit=False)

            # 将评论和被评论的文章关联起来。
            comment.post = post

            # 最终将评论数据保存进数据库，调用模型实例的 save 方法
            comment.save()
            messages.add_message(request, messages.SUCCESS, '评论发表成功！', extra_tags='success')
            # 重定向到 post 的详情页，
            # 实际上当 redirect 函数接收一个模型的实例时，它会调用这个模型实例的 get_absolute_url 方法，
            # 然后重定向到 get_absolute_url 方法返回的 URL。
            return redirect(post)

        # 检查到数据不合法，我们渲染一个预览页面，用于展示表单的错误。
        # 注意这里被评论的文章 post 也传给了模板，因为我们需要根据 post 来生成表单的提交地址。
        context = {
            'post': post,
            'form': form,
        }
        messages.add_message(request, messages.ERROR, '评论发表失败！请修改表单中的错误后重新提交。', extra_tags='danger')
        return render(request, 'comments/preview.html', context=context)

wiki/views.py
from django.shortcuts import render
from django import views

from blog.models import Category, Post


def index(request):
    categorys = Category.objects.all()
    context = {
        'categorys': categorys,
    }
    return render(request, 'wiki/index.html', context=context)


class WikiDetailView(views.View):
    def get(self, requests, cid):
        """显示某个知识库的全部文章"""
        posts = Post.objects.filter(category=cid).order_by('id')
        context = {
            'posts': posts,
        }
        return render(requests, 'wiki/detail.html', context)

templates/blog/LateX.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LaTeX</title>
    <script id="MathJax-script" async
            src="https://cdn.bootcdn.net/ajax/libs/mathjax/3.1.2/es5/tex-mml-chtml.js">
    </script>

    <script>
        MathJax = {
            tex: {
                inlineMath: [['$', '$'], ],
                displayMath: [["$$", "$$"], ],
            },
            options: {
                skipHtmlTags: [            //  HTML tags that won't be searched for math
                    'script', 'noscript', 'style', 'textarea', 'pre',
                    'code', 'annotation', 'annotation-xml'
                ],
                includeHtmlTags: {         //  HTML tags that can appear within math
                    br: '\n', wbr: '', '#comment': ''
                },
                ignoreHtmlClass: 'tex2jax_ignore',    //  class that marks tags not to search
                processHtmlClass: 'tex2jax_process',  //  class that marks tags that should be searched
                compileError: function (doc, math, err) {
                    doc.compileError(math, err)
                },
                typesetError: function (doc, math, err) {
                    doc.typesetError(math, err)
                },
            }
        };
    </script>
</head>
<body>
<p>一元二次方程 $ ax^2 + bx + c = 0 $ 的解是 $ x = {-b \pm \sqrt{b^2 - 4ac} \over 2a } $
</p>
<p>
    $$
    i \in [3, 5]
    $$
</p>
<p>
    $ \frac{a}{b} $
</p>
</body>
</html>

templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Black &amp; White</title>
    <link rel="icon" href="{% static 'blog/favicon.ico' %}">

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link href="https://cdn.bootcdn.net/ajax/libs/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

    <!-- markdown代码块高亮 -->
    <link href="https://cdn.bootcss.com/highlight.js/10.0.0/styles/github.min.css" rel="stylesheet">

    <style>
        .codehilite {
            padding: 0;
        }

        /* for block of numbers */
        .hljs-ln-numbers {
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;

            text-align: center;
            color: #ccc;
            border-right: 1px solid #CCC;
            vertical-align: top;
            padding-right: 5px;
        }

        .hljs-ln-n {
            width: 30px;
        }

        /* for block of code */
        .hljs-ln .hljs-ln-code {
            padding-left: 10px;
            white-space: pre;
        }

        .hljs {
            font-size: 15px;
        }
    </style>

    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>

    <script id="MathJax-script" async src="https://cdn.bootcdn.net/ajax/libs/mathjax/3.1.2/es5/tex-mml-chtml.js">
    </script>

    <script>
        MathJax = {
            tex: {
                inlineMath: [['$', '$'],],
                displayMath: [["$$", "$$"],],
            },
            options: {
                skipHtmlTags: [            //  HTML tags that won't be searched for math
                    'script', 'noscript', 'style', 'textarea', 'pre',
                    'code', 'annotation', 'annotation-xml'
                ],
                includeHtmlTags: {         //  HTML tags that can appear within math
                    br: '\n', wbr: '', '#comment': ''
                },
                ignoreHtmlClass: 'tex2jax_ignore',    //  class that marks tags not to search
                processHtmlClass: 'tex2jax_process',  //  class that marks tags that should be searched
                compileError: function (doc, math, err) {
                    doc.compileError(math, err)
                },
                typesetError: function (doc, math, err) {
                    doc.typesetError(math, err)
                },
            }
        };
    </script>
</head>

<body>
{# 顶部导航栏 #}
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'wiki:index' %}"
                                                        data-hover="Wiki知识库">Wiki知识库</a>
                            </li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
            </div><!-- col-md-8 -->
        </div>
    </header>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            {# 正文 #}
            {% block main %}
            {% endblock main %}
            {# 侧边栏 #}
            {% block aside %}
            {% endblock aside %}
        </div>
    </div>
</div>

<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p></p>
            </div>
        </div>
    </div>
</footer>


<script src="{% static 'blog/js/script.js' %}"></script>

<script src="https://cdn.bootcss.com/highlight.js/10.0.0/highlight.min.js"></script>
<script
        src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
<script>
    hljs.initHighlightingOnLoad();
    hljs.initLineNumbersOnLoad();
</script>
</body>

</html>

templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load blog_extras %}
{% load comments_extras %}
{% load static %}

{# 正文 #}
{% block main %}
<main class="col-md-9">
    <article class="post post-1">
        {# 文章头 #}
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a
                        href="{% url 'blog:category' post.category.id %}">{{ post.category.name }}</a></span>
                <span class="post-date"><a
                        href="{% url 'blog:archive' post.created_time.year post.created_time.month %}"><time
                            class="entry-date"
                            datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="comments-link"><a href="#comment-area"> {{ post.comment_set.count }} 评论</a></span>
                <span class="views-count"> -1 阅读</span>
            </div>
        </header>
        {# 文章内容 #}
        <div class="entry-content clearfix">
            {{ post.body|safe }}
        </div>
    </article>

    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>

        {% show_comment_form post %}

        <div class="comment-list-panel" id="comment-area">
            {% show_comments post %}
        </div>
    </section>
</main>
{% endblock %}

{# 侧边栏 #}
{% block aside %}
<aside class="col-md-3">
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        {{ post.toc|safe }}
    </div>

    {% show_recent_posts %}
    {% show_archives %}
    {% show_categories %}
    {% show_tags %}

</aside>
{% endblock %}

templates/blog/inclusions/_archives.html
<div class="widget widget-archives">
    <h3 class="widget-title">归档</h3>
    <ul>
        {% for date in date_list %}
            <li>
                <a href="{% url 'blog:archive' date.year date.month %}">{{ date.year }} 年 {{ date.month }}
                    月</a>
            </li>
        {% empty %}
            暂无归档！
        {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_categories.html
<div class="widget widget-category">
    <h3 class="widget-title">分类</h3>
    <ul>
        {% for category in category_list %}
            <li>
                <a href="{% url 'blog:category' category.id %}">{{ category.name }} <span class="post-count"></span></a>
            </li>
        {% empty %}
            暂无分类！
        {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_recent_posts.html
<div class="widget widget-recent-posts">
    <h3 class="widget-title">最新文章</h3>
    <ul>
        {% for post in recent_post_list %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
        {% empty %}
            暂无文章！
        {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_tags.html
<div class="widget widget-tag-cloud">
    <h3 class="widget-title">标签云</h3>
    <ul>
        {% for tag in tag_list %}
            <li>
                <a href="{% url 'blog:tag' tag.id %}">{{ tag.name }}</a>
            </li>
        {% empty %}
            暂无标签！
        {% endfor %}
    </ul>
</div>

templates/blog/index.html
{% extends 'blog/base.html' %}
{% load blog_extras %}
{# 正文 #}
{% block main %}
    <main class="col-md-9">
        {% for post in post_list %}
            <article class="post post-{{ post.id }}">
                <header class="entry-header">
                    <h1 class="entry-title">
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </h1>
                    <div class="entry-meta">
                        <span class="post-category"><a
                                href="{% url 'blog:category' post.category.id %}">{{ post.category.name }}</a></span>
                        <span class="post-date"><a
                                href="{% url 'blog:archive' post.created_time.year post.created_time.month %}"><time
                                class="entry-date"
                                datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                        <span class="comments-link"><a
                                href="{{ post.get_absolute_url }}#comment-area"> {{ post.comment_set.count }} 评论</a></span>
                        <span class="views-count"> -1阅读</span>
                    </div>
                </header>
                <div class="entry-content clearfix">
                    <p>{{ post.excerpt }}</p>
                    <div class="read-more cl-effect-14">
                        <a href="{% url 'blog:detail' pk=post.id %}" class="more-link">继续阅读 <span
                                class="meta-nav">→</span></a>
                    </div>
                </div>
            </article>
        {% empty %}
            <div class="no-post"> 暂时还没有发布文章！</div>
        {% endfor %}

        {# 分页  #}
        <!-- 简单分页效果
        <div class="pagination-simple">
            <a href="#">上一页</a>
            <span class="current">第 6 页 / 共 11 页</span>
            <a href="#">下一页</a>
        </div>
        -->
        <!--
        <div class="pagination">
            <ul>
                <li><a href="">1</a></li>
                <li><a href="">...</a></li>
                <li><a href="">4</a></li>
                <li><a href="">5</a></li>
                <li class="current"><a href="">6</a></li>
                <li><a href="">7</a></li>
                <li><a href="">8</a></li>
                <li><a href="">...</a></li>
                <li><a href="">11</a></li>
            </ul>
        </div>
        -->
    </main>
{% endblock %}

{# 侧边栏 #}
{% block aside %}
    <aside class="col-md-3">

        {% show_recent_posts %}
        {% show_archives %}
        {% show_categories %}
        {% show_tags %}

        <div class="rss">
            <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
        </div>
    </aside>
{% endblock %}

{# 继承的模板中，其他位置的内容不会被显示 #}

templates/comments/inclusions/_form.html
<form action="{% url 'comments:comment' post.id %}" method="post" class="comment-form">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-4">
            <label for="{{ form.name.id_for_label }}">{{ form.name.label }}：</label>
            {{ form.name }}
            {{ form.name.errors }}
        </div>
        <div class="col-md-4">
            <label for="{{ form.email.id_for_label }}">{{ form.email.label }}：</label>
            {{ form.email }}
            {{ form.email.errors }}
        </div>
        <div class="col-md-4">
            <label for="{{ form.url.id_for_label }}">{{ form.url.label }}：</label>
            {{ form.url }}
            {{ form.url.errors }}
        </div>
        <div class="col-md-12">
            <label for="{{ form.text.id_for_label }}">{{ form.text.label }}：</label>
            {{ form.text }}
            {{ form.text.errors }}
            <button type="submit" class="comment-btn">发表</button>
        </div>
    </div>    <!-- row -->
</form>

templates/comments/inclusions/_list.html
<h3>评论列表，共 <span>{{ comment_count }}</span> 条评论</h3>
<ul class="comment-list list-unstyled">
    {% for comment in comment_list %}
        <li class="comment-item">
            <span class="nickname">{{ comment.name }}</span>
            <time class="submit-date" datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
            <div class="text">
                <!--
                对评论内容使用的过滤器 linebreaks，浏览器会将换行以及连续的多个空格合并为一个空格。
                如果用户评论的内容中有换行，浏览器会将换行替换为空格，从而显示的用户评论内容就会挤成一堆。
                linebreaks 过滤器预先将换行符替换为 br HTML 标签，这样内容就能换行显示了。 -->
                {{ comment.text|linebreaks }}
            </div>
        </li>
    {% empty %}
        暂无评论
    {% endfor %}
</ul>

templates/comments/preview.html
{% extends 'blog/base.html' %}
{% load comments_extras %}

{% block main %}
    {% show_comment_form post form %}
{% endblock main %}

templates/wiki/detail.html
{% extends 'blog/base.html' %}

{% block main %}
    <div class="col-md-8">
        <a class="btn btn-default" href="{% url 'wiki:index' %}">返回Wiki主页</a>
        <table class="table table-hover">
            <thead>
            <th>#</th>
            <th>标题</th>
            <th>评论数</th>
            <th>最后修改时间</th>
            </thead>

            <tbody>
            {% for post in posts %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'blog:detail' pk=post.id %}">{{ post.title }}</a></td>
                    <td>{{ post.comment_set.count }}</td>
                    {# 修改时间, auto_now #}
                    <td>{{ post.modified_time }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/wiki/index.html
{% extends 'blog/base.html' %}

{# 正文 #}
{% block main %}
    <div class="col-md-8">
        <a class="btn btn-default" href="{% url 'blog:index' %}">返回主页</a>
        <table class="table table-hover">
            <thead>
            <th>#</th>
            <th>类别</th>
            </thead>
            <tbody>
            {% for category in categorys %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'wiki:detail' cid=category.id %}">{{ category.name }}</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock main %}